import { Router } from "express";
import { db, sequencesTable, annotationsTable } from "@workspace/db";
import { eq, desc } from "drizzle-orm";
import { z } from "zod/v4";

const router = Router();

const ExportBody = z.object({
  sequenceId: z.number().int().positive(),
  benchlingTenant: z.string().min(1),
  benchlingApiKey: z.string().min(1),
  folderId: z.string().optional(),
});

function structureLabel(s?: string | null) {
  const map: Record<string, string> = {
    alpha_helix: "α-Helix",
    beta_sheet: "β-Sheet",
    random_coil: "Random Coil",
    mixed: "Mixed",
  };
  return s ? (map[s] ?? s) : "Unknown";
}

function buildEntryMarkdown(seq: typeof sequencesTable.$inferSelect, annotations: typeof annotationsTable.$inferSelect[]): string {
  const date = new Date().toISOString().split("T")[0];
  const ipfsLine = seq.ipfsCid
    ? `\n**IPFS CID:** \`${seq.ipfsCid}\`  \n**Permanent Link:** https://ipfs.io/ipfs/${seq.ipfsCid}\n`
    : "";

  const annotationRows = annotations.length > 0
    ? annotations.map(a =>
        `| ${a.type.toUpperCase()} | ${(a.content ?? "—").slice(0, 120)} | ${a.userId.slice(0, 12)}... | +${a.tokensEarned ?? 0} $PEPTM |`
      ).join("\n")
    : "| — | No community annotations yet | — | — |";

  return [
    `# PEPTOMA Analysis Report — Sequence #${seq.id}`,
    `**Exported:** ${date}  `,
    `**Platform:** PEPTOMA (peptoma.xyz) · RRID:SCR_028424  `,
    `**Analysis Depth:** ${seq.depth?.toUpperCase() ?? "STANDARD"}`,
    "",
    "---",
    "",
    "## Sequence",
    "```",
    seq.sequence,
    "```",
    "",
    "## Classification",
    `| Property | Value |`,
    `|---|---|`,
    `| Bioactivity Label | ${seq.bioactivityLabel ?? "—"} |`,
    `| Bioactivity Score | ${seq.bioactivityScore}/100 |`,
    `| Confidence Score | ${seq.confidenceScore}/100 |`,
    `| Structure Prediction | ${structureLabel(seq.structurePrediction)} |`,
    `| Toxicity Risk | ${seq.toxicityRisk?.toUpperCase() ?? "—"} |`,
    `| Half-Life | ${seq.halfLife ?? "—"} |`,
    `| Disease Target | ${seq.diseaseTarget ?? "—"} |`,
    "",
    "## Biochemical Properties",
    `| Property | Value |`,
    `|---|---|`,
    `| Molecular Weight | ${seq.molecularWeight ? `${seq.molecularWeight} Da` : "—"} |`,
    `| Hydrophobicity Index | ${seq.hydrophobicityIndex ?? "—"} |`,
    `| Charge at pH 7 | ${seq.chargeAtPH7 ?? "—"} |`,
    "",
    "## AI Annotation Suggestions",
    ...(seq.annotationSuggestions ?? []).map((s, i) => `${i + 1}. ${s}`),
    "",
    "## Community Annotations",
    `| Type | Content | Contributor | Reward |`,
    `|---|---|---|---|`,
    annotationRows,
    "",
    "## Provenance",
    ipfsLine,
    `**PEPTOMA Sequence ID:** ${seq.id}  `,
    `**Submitted:** ${new Date(seq.createdAt).toISOString()}  `,
    `**Platform Registration:** RRID:SCR_028424 (SciCrunch)  `,
    `**Cite as:** PEPTOMA Analysis #${seq.id}, peptoma.xyz/annotate/${seq.id}`,
    "",
    "---",
    "*Generated by PEPTOMA AI Engine · Open DeSci Platform for Peptide Research · peptoma.xyz*",
  ].join("\n");
}

router.post("/benchling/export", async (req, res) => {
  const body = ExportBody.parse(req.body);

  const seq = await db.query.sequencesTable.findFirst({
    where: eq(sequencesTable.id, body.sequenceId),
  });
  if (!seq) return res.status(404).json({ error: "Sequence not found" });

  const annotations = await db.select().from(annotationsTable)
    .where(eq(annotationsTable.sequenceId, body.sequenceId))
    .orderBy(desc(annotationsTable.createdAt))
    .limit(20);

  const markdown = buildEntryMarkdown(seq, annotations);
  const today = new Date().toISOString().split("T")[0];
  const entryName = `PEPTOMA · Seq #${seq.id} · ${seq.bioactivityLabel ?? "analysis"} · ${today}`;

  const baseUrl = `https://${body.benchlingTenant}.benchling.com/api/v2`;
  const authHeader = `Basic ${Buffer.from(`${body.benchlingApiKey}:`).toString("base64")}`;

  const entryBody: Record<string, unknown> = {
    name: entryName,
    days: [
      {
        date: today,
        notes: [
          { type: "text", value: markdown },
        ],
      },
    ],
  };
  if (body.folderId) entryBody.folderId = body.folderId;

  const benchRes = await fetch(`${baseUrl}/entries`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: authHeader,
    },
    body: JSON.stringify(entryBody),
  });

  if (!benchRes.ok) {
    const errText = await benchRes.text();
    req.log.warn({ status: benchRes.status, errText }, "Benchling export failed");
    return res.status(benchRes.status).json({
      error: "Benchling API error",
      detail: errText,
      status: benchRes.status,
    });
  }

  const entry = await benchRes.json() as { id: string; webURL?: string; name: string };
  req.log.info({ sequenceId: seq.id, entryId: entry.id }, "Exported to Benchling");

  res.json({
    success: true,
    entryId: entry.id,
    entryName: entry.name,
    webURL: entry.webURL ?? `https://${body.benchlingTenant}.benchling.com`,
  });
});

router.get("/benchling/preview/:sequenceId", async (req, res) => {
  const id = parseInt(req.params.sequenceId);
  if (!id) return res.status(400).json({ error: "Invalid ID" });

  const seq = await db.query.sequencesTable.findFirst({ where: eq(sequencesTable.id, id) });
  if (!seq) return res.status(404).json({ error: "Not found" });

  const annotations = await db.select().from(annotationsTable)
    .where(eq(annotationsTable.sequenceId, id))
    .orderBy(desc(annotationsTable.createdAt))
    .limit(20);

  const markdown = buildEntryMarkdown(seq, annotations);
  res.json({ markdown, entryName: `PEPTOMA · Seq #${id} · ${seq.bioactivityLabel ?? "analysis"}` });
});

export default router;
