export type Grade = "A+" | "A" | "B" | "C";
export type StructureClass = "alpha_helix" | "beta_sheet" | "random_coil" | "mixed";
export type Status = "FDA Approved" | "Research" | "Phase III" | "Phase II" | "Pre-clinical";
export type Category = "GLP-1 Agonist" | "Peptide Therapy" | "Nootropic" | "Antimicrobial" | "Anti-aging" | "Growth Hormone";

export interface PeptideEntry {
  id: string;
  name: string;
  fullName: string;
  sequence: string;
  grade: Grade;
  halfLife: string;
  pubmedRefs: number;
  recruitingTrials: number;
  structureClass: StructureClass;
  targets: string[];
  category: Category;
  mw: string;
  status: Status;
  bioactivityScore: number;
  summary: string;
}

export const PEPTIDE_DB: PeptideEntry[] = [
  {
    id: "bpc-157",
    name: "BPC-157",
    fullName: "Body Protection Compound 157",
    sequence: "GEPPPGKPADDAGLV",
    grade: "A",
    halfLife: "~4 h (s.c.)",
    pubmedRefs: 214,
    recruitingTrials: 1,
    structureClass: "random_coil",
    targets: ["GI Protection", "Tendon Repair", "Neuroprotection"],
    category: "Peptide Therapy",
    mw: "1419.5 Da",
    status: "Research",
    bioactivityScore: 87,
    summary: "A synthetic 15-aa peptide derived from human gastric juice. Highly studied for gastroprotective, angiogenic, and tissue-repair properties. Active in nanogram doses.",
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    fullName: "GLP-1 Receptor Agonist (Ozempic/Wegovy)",
    sequence: "HAEGTFTSDVSSYLEGQAAKEFIAWLVKGR",
    grade: "A+",
    halfLife: "~7 days",
    pubmedRefs: 1946,
    recruitingTrials: 27,
    structureClass: "alpha_helix",
    targets: ["Type 2 Diabetes", "Obesity", "Cardiovascular"],
    category: "GLP-1 Agonist",
    mw: "4113.6 Da",
    status: "FDA Approved",
    bioactivityScore: 97,
    summary: "FDA-approved weekly GLP-1 agonist for T2DM and chronic weight management. Leading the peptide therapeutics revolution. C18 fatty acid conjugation enables extended half-life.",
  },
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    fullName: "GLP-1/GIP Dual Agonist (Mounjaro/Zepbound)",
    sequence: "YXEGTFTSDYSIXLDKIAQKAFVQWLIAGGPSSGAPPPS",
    grade: "A+",
    halfLife: "~5 days",
    pubmedRefs: 892,
    recruitingTrials: 39,
    structureClass: "alpha_helix",
    targets: ["Type 2 Diabetes", "Obesity", "Metabolic Syndrome"],
    category: "GLP-1 Agonist",
    mw: "4813.5 Da",
    status: "FDA Approved",
    bioactivityScore: 98,
    summary: "First-in-class dual GIP/GLP-1 receptor agonist. Outperforms semaglutide in head-to-head weight loss trials. 39 active recruiting trials as of 2025.",
  },
  {
    id: "retatrutide",
    name: "Retatrutide",
    fullName: "GLP-1/GIP/Glucagon Triple Agonist (LY3437943)",
    sequence: "YXEGTFTSDYSIXLEQAAKEFIAWLVKGR",
    grade: "A",
    halfLife: "~6 days",
    pubmedRefs: 139,
    recruitingTrials: 6,
    structureClass: "alpha_helix",
    targets: ["Obesity", "Metabolic Syndrome", "NASH"],
    category: "GLP-1 Agonist",
    mw: "4764.3 Da",
    status: "Phase III",
    bioactivityScore: 95,
    summary: "Triple GLP-1/GIP/glucagon receptor agonist in Phase III. Phase II showed up to 24% body weight reduction — highest observed for any anti-obesity agent in trials.",
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    fullName: "Copper Peptide GHK-Cu",
    sequence: "GHK",
    grade: "B",
    halfLife: "Variable",
    pubmedRefs: 312,
    recruitingTrials: 2,
    structureClass: "random_coil",
    targets: ["Wound Healing", "Anti-aging", "Hair Growth"],
    category: "Anti-aging",
    mw: "340.4 Da (free) / 402.9 Da (Cu²⁺)",
    status: "Research",
    bioactivityScore: 74,
    summary: "Naturally occurring tripeptide with high affinity for copper ions. Promotes collagen synthesis, wound repair, and has demonstrated anti-aging effects in skin studies.",
  },
  {
    id: "tb-500",
    name: "TB-500",
    fullName: "Thymosin Beta-4 Synthetic Fragment",
    sequence: "LKKTETQ",
    grade: "B",
    halfLife: "~2 days",
    pubmedRefs: 187,
    recruitingTrials: 3,
    structureClass: "random_coil",
    targets: ["Muscle Repair", "Wound Healing", "Anti-inflammation"],
    category: "Peptide Therapy",
    mw: "863.0 Da",
    status: "Research",
    bioactivityScore: 78,
    summary: "Active fragment of Thymosin Beta-4. Promotes actin polymerisation, angiogenesis, and tissue repair. Used in veterinary and research contexts for injury recovery.",
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    fullName: "Growth Hormone Releasing Peptide",
    sequence: "AIBHDNALYFKNH",
    grade: "B",
    halfLife: "~2 h",
    pubmedRefs: 94,
    recruitingTrials: 1,
    structureClass: "random_coil",
    targets: ["GH Secretion", "Muscle Growth", "Fat Loss"],
    category: "Growth Hormone",
    mw: "711.9 Da",
    status: "Research",
    bioactivityScore: 72,
    summary: "Selective GHRP-5 agonist that stimulates growth hormone release without significant cortisol or prolactin elevation. Highly selective with minimal side effects in research.",
  },
  {
    id: "epithalon",
    name: "Epithalon",
    fullName: "Epitalon / Epithalamin",
    sequence: "AEDG",
    grade: "B",
    halfLife: "~1-2 h",
    pubmedRefs: 56,
    recruitingTrials: 0,
    structureClass: "random_coil",
    targets: ["Telomerase Activation", "Anti-aging", "Circadian Regulation"],
    category: "Anti-aging",
    mw: "390.4 Da",
    status: "Pre-clinical",
    bioactivityScore: 63,
    summary: "Synthetic tetrapeptide analogue of epithalamin (pineal gland polypeptide). Russian research suggests telomerase activation and lifespan extension in animal models.",
  },
  {
    id: "selank",
    name: "Selank",
    fullName: "Selank (Semax analogue)",
    sequence: "TKPRPGP",
    grade: "B",
    halfLife: "~30 min (IN)",
    pubmedRefs: 43,
    recruitingTrials: 0,
    structureClass: "random_coil",
    targets: ["Anxiety", "Cognition", "Immune Modulation"],
    category: "Nootropic",
    mw: "751.9 Da",
    status: "Research",
    bioactivityScore: 68,
    summary: "Heptapeptide derived from tuftsin. Anxiolytic and nootropic effects documented in Russian clinical studies. Intranasal delivery. Modulates GABA and BDNF expression.",
  },
  {
    id: "ll-37",
    name: "LL-37",
    fullName: "Human Cathelicidin Antimicrobial Peptide",
    sequence: "LLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES",
    grade: "A",
    halfLife: "~hours (tissue-dependent)",
    pubmedRefs: 2341,
    recruitingTrials: 4,
    structureClass: "alpha_helix",
    targets: ["Antimicrobial", "Immunomodulation", "Wound Healing"],
    category: "Antimicrobial",
    mw: "4493.3 Da",
    status: "Phase II",
    bioactivityScore: 91,
    summary: "The only human cathelicidin. Broad-spectrum antimicrobial activity against bacteria, fungi, and enveloped viruses. Also modulates innate immune responses and promotes angiogenesis.",
  },
  {
    id: "mots-c",
    name: "MOTS-c",
    fullName: "Mitochondrial Open Reading Frame of the 12S rRNA-c",
    sequence: "MRWQEMGYIFYPRKLR",
    grade: "B",
    halfLife: "~hours",
    pubmedRefs: 78,
    recruitingTrials: 2,
    structureClass: "random_coil",
    targets: ["Metabolic Health", "Insulin Sensitivity", "Exercise Mimetic"],
    category: "Peptide Therapy",
    mw: "2174.6 Da",
    status: "Pre-clinical",
    bioactivityScore: 76,
    summary: "Mitochondria-derived peptide encoded in mitochondrial DNA. Improves insulin sensitivity, promotes glucose uptake in skeletal muscle, and increases physical performance in animal models.",
  },
  {
    id: "pt-141",
    name: "PT-141",
    fullName: "Bremelanotide (Vyleesi)",
    sequence: "SYSMEHFRWGKPV",
    grade: "A",
    halfLife: "~2.7 h",
    pubmedRefs: 128,
    recruitingTrials: 0,
    structureClass: "mixed",
    targets: ["Sexual Dysfunction", "Female Hypoactive Sexual Desire"],
    category: "Peptide Therapy",
    mw: "1025.2 Da",
    status: "FDA Approved",
    bioactivityScore: 82,
    summary: "FDA-approved melanocortin receptor agonist for hypoactive sexual desire disorder in premenopausal women. Acts centrally via MC1R and MC4R to increase sexual desire.",
  },
];

export const PEPTIDE_CATEGORIES = ["All", "GLP-1 Agonist", "Peptide Therapy", "Anti-aging", "Nootropic", "Antimicrobial", "Growth Hormone"] as const;
export const PEPTIDE_STATUSES = ["All", "FDA Approved", "Phase III", "Phase II", "Research", "Pre-clinical"] as const;
